-- Regras de cada ministério: um tipo do catálogo fixo (TipoDeRegra, no Java) por linha, com os parâmetros em JSON.
-- O tipo não tem CHECK, como auditoria.acao: um tipo novo é uma classe nova, sem migração. A rigidez diz o nível da
-- pontuação (HARD, MEDIUM ou SOFT) e o peso multiplica a penalidade. O ministério recebe o catálogo padrão ao ser
-- criado (RegraService); um tipo sem linha vale o padrão do catálogo.
create table regra (
    id            number generated by default as identity primary key,
    ministerio_id number not null,
    tipo          varchar2(40 char) not null,
    parametros    clob default '{}' not null,
    rigidez       varchar2(6 char) not null,
    peso          number(6) default 1 not null,
    ativa         number(1) default 1 not null,
    constraint fk_regra_ministerio foreign key (ministerio_id) references ministerio (id),
    constraint uk_regra_tipo unique (ministerio_id, tipo),
    constraint ck_regra_parametros check (parametros is json),
    constraint ck_regra_rigidez check (rigidez in ('HARD', 'MEDIUM', 'SOFT')),
    constraint ck_regra_peso check (peso >= 0),
    constraint ck_regra_ativa check (ativa in (0, 1))
);
