-- Vaga da escala: evento × função × posição (1 até o qtd_max da função), com a pessoa (nula = vaga vazia). A posição até
-- o qtd_min é obrigatória; acima dele, opcional. Fixada e forçada (Fase 3b) não mudam quando a escala é gerada de novo;
-- forçar exige a pessoa e a justificativa. O estado da escala (rascunho, publicada) fica no período.
-- Só a vaga vigente entra na escala: evento não cancelado, função exigida pelo evento e posição até o qtd_max. A
-- próxima geração apaga as outras. Excluir a função apaga as vagas dela (on delete cascade).
create table vaga (
    id            number generated by default as identity primary key,
    evento_id     number not null,
    funcao_id     number not null,
    posicao       number(2) not null,
    usuario_id    number,
    fixada        number(1) default 0 not null,
    forcada       number(1) default 0 not null,
    justificativa varchar2(500 char),
    atualizado_em timestamp with time zone default systimestamp not null,
    constraint fk_vaga_evento foreign key (evento_id) references evento (id),
    constraint fk_vaga_funcao foreign key (funcao_id) references funcao (id) on delete cascade,
    constraint fk_vaga_usuario foreign key (usuario_id) references usuario (id),
    constraint uk_vaga unique (evento_id, funcao_id, posicao),
    constraint ck_vaga_posicao check (posicao >= 1),
    constraint ck_vaga_fixada check (fixada in (0, 1)),
    constraint ck_vaga_forcada check (forcada in (0, 1)),
    constraint ck_vaga_forcada_justificada check (forcada = 0 or (usuario_id is not null and justificativa is not null))
);
create index ix_vaga_funcao on vaga (funcao_id);
-- A sobreposição entre ministérios procura as vagas de cada pessoa.
create index ix_vaga_usuario on vaga (usuario_id);
