-- Usuários do sistema. LGPD: só nome, e-mail e telefone.
create table usuario (
    id            number generated by default as identity primary key,
    nome          varchar2(150 char) not null,
    email         varchar2(254 char) not null,
    telefone      varchar2(20 char),
    senha_hash    varchar2(100 char) not null,
    admin         boolean default false not null,
    ativo         boolean default true not null,
    criado_em     timestamp with time zone default systimestamp not null,
    atualizado_em timestamp with time zone default systimestamp not null,
    constraint uk_usuario_email unique (email),
    constraint ck_usuario_email_minusculo check (email = lower(email))
);
