-- Ministérios e o que varia por ministério: membresias, funções, níveis e habilitações.
-- Compatível com Oracle 19c (produção): flags em NUMBER(1), sem BOOLEAN.
create table ministerio (
    id        number generated by default as identity primary key,
    nome      varchar2(80 char) not null,
    cor       varchar2(10 char) not null,
    icone     varchar2(40 char) not null,
    criado_em timestamp with time zone default systimestamp not null,
    constraint ck_ministerio_cor check (cor in ('MINT', 'ROSE', 'LEMON'))
);
-- Nome único sem diferenciar maiúsculas: "Mídia" e "mídia" são o mesmo ministério.
create unique index uk_ministerio_nome on ministerio (lower(nome));

-- Usuário × ministério. O gerente é por ministério.
create table membresia (
    id            number generated by default as identity primary key,
    usuario_id    number not null,
    ministerio_id number not null,
    gerente       number(1) default 0 not null,
    criado_em     timestamp with time zone default systimestamp not null,
    constraint fk_membresia_usuario foreign key (usuario_id) references usuario (id),
    constraint fk_membresia_ministerio foreign key (ministerio_id) references ministerio (id),
    constraint uk_membresia unique (usuario_id, ministerio_id),
    constraint ck_membresia_gerente check (gerente in (0, 1))
);
create index ix_membresia_ministerio on membresia (ministerio_id);

-- Função de um ministério (Projeção, Transmissão) e quantas pessoas ela pede por evento.
create table funcao (
    id            number generated by default as identity primary key,
    ministerio_id number not null,
    nome          varchar2(60 char) not null,
    icone         varchar2(40 char) not null,
    qtd_min       number(2) not null,
    qtd_max       number(2) not null,
    constraint fk_funcao_ministerio foreign key (ministerio_id) references ministerio (id),
    constraint ck_funcao_qtd check (qtd_min >= 0 and qtd_max >= 1 and qtd_max >= qtd_min)
);
create unique index uk_funcao_nome on funcao (ministerio_id, lower(nome));

-- Nível de experiência do ministério (Iniciante, Experiente), do menor para o maior.
create table nivel (
    id            number generated by default as identity primary key,
    ministerio_id number not null,
    nome          varchar2(40 char) not null,
    ordem         number(3) not null,
    constraint fk_nivel_ministerio foreign key (ministerio_id) references ministerio (id),
    constraint uk_nivel_ordem unique (ministerio_id, ordem),
    constraint ck_nivel_ordem check (ordem >= 1)
);
create unique index uk_nivel_nome on nivel (ministerio_id, lower(nome));

-- O que o membro pode fazer: uma função, em um nível, atribuído pelo gerente.
create table habilitacao (
    id         number generated by default as identity primary key,
    usuario_id number not null,
    funcao_id  number not null,
    nivel_id   number not null,
    constraint fk_habilitacao_usuario foreign key (usuario_id) references usuario (id),
    constraint fk_habilitacao_funcao foreign key (funcao_id) references funcao (id),
    constraint fk_habilitacao_nivel foreign key (nivel_id) references nivel (id),
    constraint uk_habilitacao unique (usuario_id, funcao_id)
);
create index ix_habilitacao_funcao on habilitacao (funcao_id);
create index ix_habilitacao_nivel on habilitacao (nivel_id);
