-- Registro das ações de gerentes e admins que mexem em pessoas e escalas (quem, onde, sobre quem, o quê).
create table auditoria (
    id              number generated by default as identity primary key,
    autor_id        number not null,
    ministerio_id   number,
    alvo_usuario_id number,
    acao            varchar2(40 char) not null,
    descricao       varchar2(500 char) not null,
    criado_em       timestamp with time zone default systimestamp not null,
    constraint fk_auditoria_autor foreign key (autor_id) references usuario (id),
    constraint fk_auditoria_ministerio foreign key (ministerio_id) references ministerio (id),
    constraint fk_auditoria_alvo foreign key (alvo_usuario_id) references usuario (id)
);
create index ix_auditoria_ministerio on auditoria (ministerio_id, criado_em);
create index ix_auditoria_autor on auditoria (autor_id);
create index ix_auditoria_alvo on auditoria (alvo_usuario_id);
