-- Eventos de cada ministério: modelos recorrentes (Culto de domingo, 18h00), períodos (um por mês) e os eventos.
-- Datas e horários são os da igreja, no fuso America/Sao_Paulo, sem fuso no banco: o horário em minutos desde a
-- meia-noite e a data como DATE.
create table modelo_evento (
    id              number generated by default as identity primary key,
    ministerio_id   number not null,
    nome            varchar2(80 char) not null,
    dia_semana      number(1) not null,
    horario_minutos number(4) not null,
    ativo           number(1) default 1 not null,
    constraint fk_modelo_evento_ministerio foreign key (ministerio_id) references ministerio (id),
    constraint ck_modelo_evento_dia check (dia_semana between 1 and 7),
    constraint ck_modelo_evento_horario check (horario_minutos between 0 and 1439),
    constraint ck_modelo_evento_ativo check (ativo in (0, 1))
);
create index ix_modelo_evento_ministerio on modelo_evento (ministerio_id);

-- O mês de um ministério: a trava da disponibilidade e o estado da escala ficam aqui.
create table periodo (
    id                      number generated by default as identity primary key,
    ministerio_id           number not null,
    ano                     number(4) not null,
    mes                     number(2) not null,
    disponibilidade_travada number(1) default 0 not null,
    status_escala           varchar2(10 char) default 'RASCUNHO' not null,
    constraint fk_periodo_ministerio foreign key (ministerio_id) references ministerio (id),
    constraint uk_periodo unique (ministerio_id, ano, mes),
    constraint ck_periodo_mes check (mes between 1 and 12),
    constraint ck_periodo_travada check (disponibilidade_travada in (0, 1)),
    constraint ck_periodo_status check (status_escala in ('RASCUNHO', 'PUBLICADA'))
);

-- Evento de um período: gerado de um modelo (modelo_id) ou avulso (modelo_id nulo).
create table evento (
    id              number generated by default as identity primary key,
    ministerio_id   number not null,
    periodo_id      number not null,
    modelo_id       number,
    nome            varchar2(80 char) not null,
    data_evento     date not null,
    horario_minutos number(4) not null,
    cancelado       number(1) default 0 not null,
    constraint fk_evento_ministerio foreign key (ministerio_id) references ministerio (id),
    constraint fk_evento_periodo foreign key (periodo_id) references periodo (id),
    constraint fk_evento_modelo foreign key (modelo_id) references modelo_evento (id),
    constraint ck_evento_horario check (horario_minutos between 0 and 1439),
    constraint ck_evento_cancelado check (cancelado in (0, 1))
);
-- Um evento por modelo e data, para gerar o mês de novo sem duplicar (nem recriar um cancelado). Num unique comum o
-- Oracle compararia também os avulsos (modelo nulo) da mesma data; o CASE deixa os avulsos fora do índice.
create unique index uk_evento_modelo_data on evento (
    case when modelo_id is not null then modelo_id end,
    case when modelo_id is not null then data_evento end
);
create index ix_evento_periodo on evento (periodo_id, data_evento);
create index ix_evento_ministerio_data on evento (ministerio_id, data_evento);
