-- Disponibilidade: a resposta de cada pessoa a cada evento (Pode, Não pode; Prefiro não fica para a Fase 5).
-- Uma linha por usuário e evento: marcar de novo atualiza a mesma linha. Sem linha, a pessoa não respondeu, e sem
-- resposta ela conta como indisponível na geração da escala.
-- data_na_resposta e horario_na_resposta_minutos guardam como o evento estava quando a pessoa respondeu: se o horário
-- (ou a data de um avulso) mudar depois, a resposta continua e a tela avisa. marcado_por_id é quem marcou: a própria
-- pessoa ou o gerente, em nome dela.
create table disponibilidade (
    id                          number generated by default as identity primary key,
    usuario_id                  number not null,
    evento_id                   number not null,
    resposta                    varchar2(12 char) not null,
    data_na_resposta            date not null,
    horario_na_resposta_minutos number(4) not null,
    marcado_por_id              number not null,
    atualizado_em               timestamp with time zone default systimestamp not null,
    constraint fk_disponibilidade_usuario foreign key (usuario_id) references usuario (id),
    constraint fk_disponibilidade_evento foreign key (evento_id) references evento (id),
    constraint fk_disponibilidade_marcado_por foreign key (marcado_por_id) references usuario (id),
    constraint uk_disponibilidade unique (usuario_id, evento_id),
    constraint ck_disponibilidade_resposta check (resposta in ('PODE', 'NAO_PODE', 'PREFERE_NAO')),
    constraint ck_disponibilidade_horario check (horario_na_resposta_minutos between 0 and 1439)
);
create index ix_disponibilidade_evento on disponibilidade (evento_id);
create index ix_disponibilidade_marcado_por on disponibilidade (marcado_por_id);
